version: '3.8'

networks:
  focushabit-network:
    driver: bridge

services:
  app:
    build: ./app
    container_name: focus-habit-app
    restart: always
    ports:
      - "8000:8000"
    networks:
      - focushabit-network

  nginx:
    image: nginx:latest
    container_name: focus-habit-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - app
    networks:
      - focushabit-network

  certbot:
    image: certbot/certbot
    container_name: focus-habit-certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - focushabit-network

  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "9999:8080"
    restart: always
    networks:
      - focushabit-network