name: Focus-habit BE continuous-deployment

on:
  push:
    branches: ["feature/landmarks-only-mode"]

permissions:
  contents: read

jobs:
  CD:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GCP_SSHKEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.GCP_HOST }} >> ~/.ssh/known_hosts
        shell: bash

      - name: Deploy Application with Docker Compose
        run: |
          ssh -T -i ~/.ssh/id_rsa ${{ secrets.GCP_USER }}@${{ secrets.GCP_HOST }} << 'EOF'
            cd Focus_habit_BE
            git pull origin feature/landmarks-only-mode
            docker-compose down --remove-orphans
            docker-compose up -d --build
            docker image prune -f
          EOF
        shell: bash